package engine

/// <!- FILE: `engine_test.go`
/// <!- PURPOSE: Table-driven tests for every rule, edit application, and gofmt stability.

import (
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

const fname = "test.go"

type fixture struct {
	name string
	src  string
	/// wantRule counts at least these many violations of each rule (use map for exact).
	wantRule   map[Rule]int
	wantNoRule []Rule
	/// wantSubstr in the applied output (post-rewrite).
	wantSubstr   string
	wantNoSubstr string
	/// stability check: Apply output must be gofmt-stable (default true).
	stable bool
}

func runFixture(t *testing.T, fx fixture) {
	t.Helper()
	res, err := Analyze([]byte(fx.src), fname)
	if err != nil {
		t.Fatalf("parse error: %v", err)
	}
	if fx.wantRule != nil {
		got := map[Rule]int{}
		for _, v := range res.Violations {
			got[v.Rule]++
		}
		for r, n := range fx.wantRule {
			if got[r] != n {
				t.Errorf("rule %s: got %d, want %d (violations=%+v)", r, got[r], n, got)
			}
		}
	}
	for _, r := range fx.wantNoRule {
		for _, v := range res.Violations {
			if v.Rule == r {
				t.Errorf("rule %s should not fire; got: %s", r, v.Message)
			}
		}
	}
	out := Apply([]byte(fx.src), res.Edits)
	if fx.wantSubstr != "" && !strings.Contains(string(out), fx.wantSubstr) {
		t.Errorf("output missing %q\nGOT:\n%s", fx.wantSubstr, out)
	}
	if fx.wantNoSubstr != "" && strings.Contains(string(out), fx.wantNoSubstr) {
		t.Errorf("output unexpectedly contains %q\nGOT:\n%s", fx.wantNoSubstr, out)
	}
	stable := fx.stable
	if !stable {
		return
	}
	fmtOut, ferr := format.Source(out)
	if ferr != nil {
		t.Fatalf("gofmt failed on output: %v\nOUT:\n%s", ferr, out)
	}
	if string(fmtOut) != string(out) {
		t.Errorf("gofmt-unstable: output is not byte-exact under gofmt\nGOT:\n%s\nFMT:\n%s", out, fmtOut)
	}
}

func TestIsGenerated(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{"marker before package", "// Code generated by foogen. DO NOT EDIT.\n\npackage x\n", true},
		{"no marker", "package x\n", false},
		{"marker after package", "package x\n// Code generated by foogen. DO NOT EDIT.\n", false},
		{"marker without exact suffix", "// Code generated by foogen. DO NOT MANUALLY EDIT.\n", false},
		{"copyright then marker", "// (c) Acme\n// Code generated by foogen. DO NOT EDIT.\npackage x\n", true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := IsGenerated([]byte(c.src)); got != c.want {
				t.Errorf("got %v, want %v", got, c.want)
			}
		})
	}
}

func TestMapASCII(t *testing.T) {
	cases := []struct {
		name   string
		in     string
		want   string
		wantOK bool
	}{
		{"plain ascii", "plain ascii", "plain ascii", false},
		{"em-dash", "a \u2014 b", "a - b", true},
		{"arrow", "x \u2192 y", "x -> y", true},
		{"plusminus", "n\u00B11", "n+/-1", true},
		{"quotes", "\u201csmart\u201d \u2018q\u2019", `"smart" 'q'`, true},
		{"ellipsis", "a\u2026b", "a...b", true},
		{"unmappable thai passes through", "\u0E01\u0E32\u0E23", "\u0E01\u0E32\u0E23", false},
		{"mixed: symbol fixed, thai kept", "ok \u2014 \u0E01", "ok - \u0E01", true},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			got, ok := mapASCII(c.in)
			if ok != c.wantOK {
				t.Errorf("ok=%v want %v (got %q)", ok, c.wantOK, got)
			}
			if ok && got != c.want {
				t.Errorf("got %q, want %q", got, c.want)
			}
		})
	}
}

func TestASCIIPairs(t *testing.T) {
	got := asciiPairs("a \u2014 b \u2192 c \u2014 d")
	want := "\u2014 -> -, \u2192 -> ->"
	if got != want {
		t.Errorf("got %q, want %q", got, want)
	}
	if asciiPairs("plain") != "" {
		t.Errorf("plain string should yield empty pairs")
	}
}

func TestFuncDocDelete(t *testing.T) {
	runFixture(t, fixture{
		name:         "plain godoc above func deleted",
		src:          "package x\n\n// CreateOrder creates an order.\nfunc CreateOrder() {}\n",
		wantRule:     map[Rule]int{RFuncDoc: 1},
		wantNoSubstr: "CreateOrder creates",
		stable:       true,
	})
}

func TestFuncDocSwaggerKept(t *testing.T) {
	runFixture(t, fixture{
		name:       "swagger above func kept",
		src:        "package x\n\n// @Summary list\n// @Router /x [get]\nfunc List() {}\n",
		wantNoRule: []Rule{RFuncDoc},
		wantSubstr: "// @Summary list",
		stable:     true,
	})
}

func TestFuncDocDirectiveKept(t *testing.T) {
	runFixture(t, fixture{
		name:       "nolint directive above func kept",
		src:        "package x\n\n//nolint:unused\nfunc F() {}\n",
		wantNoRule: []Rule{RFuncDoc, RTagSlash},
		wantSubstr: "//nolint:unused",
		stable:     true,
	})
}

func TestFuncDocFormula(t *testing.T) {
	res, err := Analyze([]byte("package x\n\n// <!- FORMULA: n = -LOG(x)\n// <!- tag line\nfunc F() {}\n"), fname)
	if err != nil {
		t.Fatal(err)
	}
	var found bool
	for _, v := range res.Violations {
		if v.Rule == RFuncDoc && strings.Contains(v.Message, "FORMULA") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected RFuncDoc message mentioning FORMULA; got %+v", res.Violations)
	}
	// the tag lines must NOT also trigger RTagSlash: they are inside the deleted group.
	for _, v := range res.Violations {
		if v.Rule == RTagSlash {
			t.Errorf("tag-slash should not fire on lines being deleted: %s", v.Message)
		}
	}
}

func TestDetachType(t *testing.T) {
	runFixture(t, fixture{
		name:       "/// attached above type detached",
		src:        "package x\n\n/// <!- MODEL: order\ntype Order struct{}\n",
		wantRule:   map[Rule]int{RDetach: 1},
		wantNoRule: []Rule{RFuncDoc},
		wantSubstr: "/// <!- MODEL: order\n\ntype Order struct{}",
		stable:     true,
	})
}

func TestDetachAlreadyDetached(t *testing.T) {
	runFixture(t, fixture{
		name:       "blank line between /// and type: no detach",
		src:        "package x\n\n/// <!- MODEL\n\ntype T struct{}\n",
		wantNoRule: []Rule{RDetach},
		stable:     true,
	})
}

func TestDetachConstKeyword(t *testing.T) {
	runFixture(t, fixture{
		name:       "/// above const ( block detached",
		src:        "package x\n\n/// <!- LIMITS\nconst (\n\tA = 1\n)\n",
		wantRule:   map[Rule]int{RDetach: 1},
		wantSubstr: "/// <!- LIMITS\n\nconst (",
		stable:     true,
	})
}

func TestDetachTopLevelConstNonParen(t *testing.T) {
	runFixture(t, fixture{
		name:       "/// above const X detached",
		src:        "package x\n\n/// <!- LIMITS\nconst MaxT = 10\n",
		wantRule:   map[Rule]int{RDetach: 1},
		wantSubstr: "/// <!- LIMITS\n\nconst MaxT",
		stable:     true,
	})
}

func TestSpecLevelSurvives(t *testing.T) {
	// /// above a spec inside const (...) is already gofmt-stable; no detach needed.
	runFixture(t, fixture{
		name:       "/// inside const block spec survives",
		src:        "package x\n\nconst (\n\t/// <!- LIMITS\n\tMaxN = 5\n)\n",
		wantNoRule: []Rule{RDetach},
		stable:     true,
	})
}

func TestTagSlashBodyTag(t *testing.T) {
	runFixture(t, fixture{
		name:       "// <!- inside function body rewritten to ///",
		src:        "package x\n\nfunc F() {\n\t// <!- STEP: compute\n\tx := 1\n\t_ = x\n}\n",
		wantRule:   map[Rule]int{RTagSlash: 1},
		wantSubstr: "/// <!- STEP: compute",
		stable:     true,
	})
}

func TestTagSlashStructField(t *testing.T) {
	runFixture(t, fixture{
		name:       "// trailing struct annotation rewritten to ///",
		src:        "package x\n\ntype T struct {\n\tID string // primary key\n}\n",
		wantRule:   map[Rule]int{RTagSlash: 1},
		wantSubstr: "ID string /// primary key",
		stable:     true,
	})
}

func TestTagSlashConstBlockSpecDoc(t *testing.T) {
	runFixture(t, fixture{
		name:       "// spec doc inside const (...) rewritten to ///",
		src:        "package x\n\nconst (\n\t// MaxN is the cap.\n\tMaxN = 5\n)\n",
		wantRule:   map[Rule]int{RTagSlash: 1},
		wantSubstr: "/// MaxN is the cap.",
		stable:     true,
	})
}

func TestBodyPlainRemarkUntouched(t *testing.T) {
	runFixture(t, fixture{
		name:       "plain // remark in function body left alone",
		src:        "package x\n\nfunc F() {\n\t// just a casual remark\n\tx := 1\n\t_ = x\n}\n",
		wantNoRule: []Rule{RTagSlash, RFuncDoc},
		wantSubstr: "// just a casual remark",
		stable:     true,
	})
}

func TestAlreadyTripleSlashUntouched(t *testing.T) {
	runFixture(t, fixture{
		name:       "/// in struct zone not rewritten again",
		src:        "package x\n\ntype T struct {\n\t/// <!- GROUP\n\tA string\n}\n",
		wantNoRule: []Rule{RTagSlash},
		stable:     true,
	})
}

func TestBlockCommentSingle(t *testing.T) {
	runFixture(t, fixture{
		name:         "/* foo */ rewritten to /// line",
		src:          "package x\n\n/* foo bar */\nvar _ = 1\n",
		wantRule:     map[Rule]int{RBlock: 1},
		wantSubstr:   "/// foo bar",
		wantNoSubstr: "/*",
		stable:       true,
	})
}

func TestBlockCommentMultiline(t *testing.T) {
	runFixture(t, fixture{
		name:       "multiline block comment split into /// lines",
		src:        "package x\n\n/* line one\n   line two */\nvar _ = 1\n",
		wantRule:   map[Rule]int{RBlock: 1},
		wantSubstr: "/// line one\n/// line two",
		stable:     true,
	})
}

func TestBlockCommentEmpty(t *testing.T) {
	runFixture(t, fixture{
		name:         "empty block comment deleted",
		src:          "package x\n\n/**/\nvar _ = 1\n",
		wantRule:     map[Rule]int{RBlock: 1},
		wantNoSubstr: "/**/",
		stable:       true,
	})
}

func TestASCIISymbol(t *testing.T) {
	runFixture(t, fixture{
		name:       "em-dash and smart quotes normalized in comment",
		src:        "package x\n\nvar y = 1 // \u2014 \u201csmart\u201d \u00B11\n",
		wantRule:   map[Rule]int{RAscii: 1},
		wantSubstr: "- \"smart\" +/-1",
		stable:     true,
	})
}

func TestASCIIThaiAcceptable(t *testing.T) {
	// Pure Thai text: no mappable symbols, no violation at all.
	res, err := Analyze([]byte("package x\n\n// \u0E01\u0E32\u0E23 thai text\nvar _ = 1\n"), fname)
	if err != nil {
		t.Fatal(err)
	}
	for _, v := range res.Violations {
		if v.Rule == RAscii {
			t.Errorf("pure Thai comment must not be flagged: %s", v.Message)
		}
	}

	// Mixed Thai + em-dash: only the symbol is normalized, Thai preserved.
	src := []byte("package x\n\n// \u0E01\u0E32\u0E23 \u2014 data\nvar _ = 1\n")
	res, err = Analyze(src, fname)
	if err != nil {
		t.Fatal(err)
	}
	found := false
	for _, v := range res.Violations {
		if v.Rule == RAscii {
			if !v.Fixable {
				t.Errorf("mixed symbol+Thai should be Fixable")
			}
			found = true
		}
	}
	if !found {
		t.Fatal("expected one fixable ascii violation")
	}
	out := Apply(src, res.Edits)
	want := "// \u0E01\u0E32\u0E23 - data"
	if !strings.Contains(string(out), want) {
		t.Errorf("em-dash fixed and Thai preserved; want %q\nGOT:\n%s", want, out)
	}
}

func TestHeadingBothMissing(t *testing.T) {
	runFixture(t, fixture{
		name:       "FILE and PURPOSE both missing injected after package",
		src:        "package x\n\nimport \"fmt\"\n\nvar _ = fmt.Print\n",
		wantRule:   map[Rule]int{RHeadingFile: 1, RHeadingPurp: 1},
		wantSubstr: "/// <!- FILE: `" + fname + "`\n/// <!- PURPOSE: TODO - fill in.",
		stable:     true,
	})
}

func TestHeadingPurposeMissing(t *testing.T) {
	runFixture(t, fixture{
		name:       "FILE present, PURPOSE missing",
		src:        "package x\n\n/// <!- FILE: `test.go`\n\nimport \"fmt\"\n\nvar _ = fmt.Print\n",
		wantRule:   map[Rule]int{RHeadingPurp: 1},
		wantNoRule: []Rule{RHeadingFile},
		wantSubstr: "/// <!- PURPOSE: TODO - fill in.",
		stable:     true,
	})
}

func TestHeadingPurposePlaceholder(t *testing.T) {
	res, err := Analyze([]byte("package x\n\n/// <!- FILE: `test.go`\n/// <!- PURPOSE: TODO - fill in.\n\nfunc F() {}\n"), fname)
	if err != nil {
		t.Fatal(err)
	}
	var found bool
	for _, v := range res.Violations {
		if v.Rule == RHeadingPurp && !v.Fixable && strings.Contains(v.Message, "TODO") {
			found = true
		}
	}
	if !found {
		t.Errorf("expected report-only PURPOSE placeholder violation; got %+v", res.Violations)
	}
}

func TestHeadingCompleteNoViolation(t *testing.T) {
	runFixture(t, fixture{
		name:       "FILE + real PURPOSE present: no heading violation",
		src:        "package x\n\n/// <!- FILE: `test.go`\n/// <!- PURPOSE: Does the thing.\n\nfunc F() {}\n",
		wantNoRule: []Rule{RHeadingFile, RHeadingPurp},
		stable:     true,
	})
}

func TestSlopReportOnly(t *testing.T) {
	res, err := Analyze([]byte("package x\n\nfunc F() {\n\t// This function computes the value\n\tx := 1\n\t_ = x\n}\n"), fname)
	if err != nil {
		t.Fatal(err)
	}
	var found bool
	for _, v := range res.Violations {
		if v.Rule == RSlop {
			if v.Fixable {
				t.Errorf("slop should be report-only, not Fixable")
			}
			found = true
		}
	}
	if !found {
		t.Errorf("expected a slop violation; got %+v", res.Violations)
	}
}

func TestChainingTagRewriteTriggersDetach(t *testing.T) {
	// // <!- above a type: rewrite to /// must also insert a blank line,
	// otherwise gofmt rewrites the /// back to // /.
	runFixture(t, fixture{
		name:       "// <!- above type: rewrite + detach in one pass",
		src:        "package x\n\n// <!- MODEL: T\ntype T struct{}\n",
		wantRule:   map[Rule]int{RTagSlash: 1, RDetach: 1},
		wantSubstr: "/// <!- MODEL: T\n\ntype T struct{}",
		stable:     true,
	})
}

func TestChainingDetachedOncePerDecl(t *testing.T) {
	// Several tag lines above one decl chain rewrites but must emit exactly
	// one detach violation and one blank-line edit.
	src := []byte("package x\n\n// <!- TAG: a\n// <!- TAG: b\n// <!- TAG: c\nconst (\n\tA = 1\n)\n")
	res, err := Analyze(src, fname)
	if err != nil {
		t.Fatal(err)
	}
	detachCount := 0
	for _, v := range res.Violations {
		if v.Rule == RDetach {
			detachCount++
		}
	}
	if detachCount != 1 {
		t.Errorf("got %d detach violations, want 1; violations=%+v", detachCount, res.Violations)
	}
	inserts := 0
	for _, e := range res.Edits {
		if e.New == "\n" && e.Start == e.End {
			inserts++
		}
	}
	if inserts != 1 {
		t.Errorf("got %d blank-line insert edits, want 1", inserts)
	}
	out := Apply(src, res.Edits)
	want := "/// <!- TAG: c\n\nconst ("
	if !strings.Contains(string(out), want) {
		t.Errorf("want %q\nGOT:\n%s", want, out)
	}
	fmtOut, ferr := format.Source(out)
	if ferr != nil || string(fmtOut) != string(out) {
		t.Errorf("not gofmt-stable: %v", ferr)
	}
}

func TestChainingTagAboveImport(t *testing.T) {
	// // <!- above import gets rewritten to ///; gofmt leaves import-attached /// alone.
	runFixture(t, fixture{
		name:       "// <!- above import rewritten (import heading survives gofmt)",
		src:        "package x\n\n// <!- GROUP: imports\nimport \"fmt\"\n\nvar _ = fmt.Print\n",
		wantRule:   map[Rule]int{RTagSlash: 1},
		wantSubstr: "/// <!- GROUP: imports\n\nimport",
		stable:     true,
	})
}

func TestParseError(t *testing.T) {
	_, err := Analyze([]byte("package x\n\nfunc broken(\n"), fname)
	if err == nil {
		t.Fatal("expected parse error, got nil")
	}
}

func TestApplyNoEdits(t *testing.T) {
	src := []byte("package x\n")
	if got := Apply(src, nil); string(got) != string(src) {
		t.Errorf("Apply with no edits should return src unchanged")
	}
}

func TestApplyCollapseNewlines(t *testing.T) {
	// Two deletions one after another that would leave 3+ newlines collapse to one blank.
	src := []byte("package x\n\n// c1\n// c2\nfunc F() {}\n")
	res, err := Analyze(src, fname)
	if err != nil {
		t.Fatal(err)
	}
	out := Apply(src, res.Edits)
	if strings.Contains(string(out), "// c1") || strings.Contains(string(out), "// c2") {
		t.Errorf("comments not deleted: %s", out)
	}
	if strings.Contains(string(out), "\n\n\n") {
		t.Errorf("triple newline not collapsed: %q", out)
	}
	fmtOut, ferr := format.Source(out)
	if ferr != nil || string(fmtOut) != string(out) {
		t.Errorf("output not gofmt-stable: err=%v", ferr)
	}
}

func TestApplyInsertionAndDeletion(t *testing.T) {
	// Combine a heading injection (insert) with a func-doc delete (range) and assert stable.
	src := []byte("package x\n\n// CreateOrder creates an order.\nfunc CreateOrder() {}\n")
	res, err := Analyze(src, fname)
	if err != nil {
		t.Fatal(err)
	}
	out := Apply(src, res.Edits)
	if strings.Contains(string(out), "CreateOrder creates") {
		t.Errorf("func doc not deleted")
	}
	if !strings.Contains(string(out), "/// <!- FILE:") {
		t.Errorf("heading not injected")
	}
	fmtOut, ferr := format.Source(out)
	if ferr != nil || string(fmtOut) != string(out) {
		t.Errorf("combined edit not gofmt-stable: err=%v\nOUT:\n%s", ferr, out)
	}
}

func TestEndLineRangeForMultiLineFuncDoc(t *testing.T) {
	src := []byte("package x\n\n// line one\n// line two\n// line three\nfunc F() {}\n")
	res, err := Analyze(src, fname)
	if err != nil {
		t.Fatal(err)
	}
	for _, v := range res.Violations {
		if v.Rule == RFuncDoc {
			if v.EndLine <= v.Line {
				t.Errorf("multi-line func-doc violation should have EndLine > Line; got %d-%d", v.Line, v.EndLine)
			}
			return
		}
	}
	t.Errorf("no RFuncDoc violation found")
}

func TestIsSwaggerOrDirectiveBranches(t *testing.T) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, fname, "package x\n\n/* block comment */\nfunc F() {}\n", parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	fd := f.Decls[0].(*ast.FuncDecl)
	if isSwaggerOrDirective(fd.Doc) {
		t.Errorf("block comment doc is not swagger/directive")
	}

	f2, err := parser.ParseFile(fset, fname, "package x\n\n// @Summary x\nfunc G() {}\n", parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	fd2 := f2.Decls[0].(*ast.FuncDecl)
	if !isSwaggerOrDirective(fd2.Doc) {
		t.Errorf("@-prefixed line should count as swagger")
	}
}

func TestApplyOverlapGuard(t *testing.T) {
	src := []byte("0123456789ABCDEF")
	edits := []Edit{{Start: 0, End: 10, New: "Y"}, {Start: 5, End: 15, New: "X"}}
	out := Apply(src, edits)
	// The [0,10) edit overlaps the already-applied [5,15) edit and is skipped.
	if !strings.Contains(string(out), "X") {
		t.Errorf("non-overlapping edit should apply, got %q", out)
	}
	if strings.Contains(string(out), "Y") {
		t.Errorf("overlapping edit must be skipped, got %q", out)
	}
}

func TestApplyOutOfRange(t *testing.T) {
	out := Apply([]byte("abc"), []Edit{{Start: -1, End: 1, New: "X"}, {Start: 0, End: 99, New: "Y"}})
	if string(out) != "abc" {
		t.Errorf("out-of-range edits must be skipped, got %q", out)
	}
}
