package main

/// <!- FILE: `main_test.go`
/// <!- PURPOSE: CLI tests via run(): dry-run/fix/diff modes, file collection, helpers.

import (
	"bytes"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeFile(t *testing.T, dir, name, content string) string {
	t.Helper()
	p := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	return p
}

func runCLI(t *testing.T, args ...string) (int, string, string) {
	t.Helper()
	var out, errb bytes.Buffer
	code := run(args, &out, &errb)
	return code, out.String(), errb.String()
}

func TestRunUsageNoPaths(t *testing.T) {
	code, _, errb := runCLI(t)
	if code != 2 {
		t.Errorf("exit = %d, want 2", code)
	}
	if !strings.Contains(errb, "usage: rscf") {
		t.Errorf("stderr missing usage, got: %s", errb)
	}
}

func TestRunHelp(t *testing.T) {
	code, _, errb := runCLI(t, "--help")
	if code != 0 {
		t.Errorf("exit = %d, want 0", code)
	}
	if !strings.Contains(errb, "dry run (default)") {
		t.Errorf("stderr missing usage text, got: %s", errb)
	}
}

func TestRunUnknownFlag(t *testing.T) {
	code, _, errb := runCLI(t, "--bogus", ".")
	if code != 2 {
		t.Errorf("exit = %d, want 2", code)
	}
	if !strings.Contains(errb, `unknown flag "--bogus"`) {
		t.Errorf("stderr missing unknown flag message, got: %s", errb)
	}
}

func TestRunFixAndDiffMutuallyExclusive(t *testing.T) {
	code, _, errb := runCLI(t, "--fix", "--diff", ".")
	if code != 2 {
		t.Errorf("exit = %d, want 2", code)
	}
	if !strings.Contains(errb, "mutually exclusive") {
		t.Errorf("stderr missing mutual exclusion message, got: %s", errb)
	}
}

func TestRunNonexistentPath(t *testing.T) {
	code, _, errb := runCLI(t, "/no/such/dir")
	if code != 0 {
		t.Errorf("exit = %d, want 0 (stat error is non-fatal)", code)
	}
	if !strings.Contains(errb, "stat /no/such/dir") {
		t.Errorf("stderr missing stat error, got: %s", errb)
	}
}

func TestRunParseError(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "broken.go", "package x\nfunc broken(\n")
	code, out, errb := runCLI(t, dir)
	if code != 0 {
		t.Errorf("exit = %d, want 0 (parse error is non-fatal)", code)
	}
	if !strings.Contains(errb, "parse ") {
		t.Errorf("stderr missing parse error, got: %s", errb)
	}
	if !strings.Contains(out, "parse errors: 1") {
		t.Errorf("summary missing parse error count, got: %s", out)
	}
}

func TestRunDryRunPrintsInstructionsAndDoesNotWrite(t *testing.T) {
	dir := t.TempDir()
	src := "package x\n\n// CreateOrder creates an order.\nfunc CreateOrder() {}\n"
	p := writeFile(t, dir, "a.go", src)

	code, out, _ := runCLI(t, dir)
	if code != 1 {
		t.Errorf("exit = %d, want 1 (violations present)", code)
	}
	if !strings.Contains(out, "bottom-up") {
		t.Errorf("missing bottom-up hint, got: %s", out)
	}
	if !strings.Contains(out, "a.go:3 [func-doc] delete this comment group") {
		t.Errorf("missing addressed instruction, got: %s", out)
	}
	if !strings.Contains(out, "func-doc         1") {
		t.Errorf("missing rule count in summary, got: %s", out)
	}
	got, err := os.ReadFile(p)
	if err != nil || string(got) != src {
		t.Errorf("dry run must not write files")
	}
}

func TestRunDryRangeInstruction(t *testing.T) {
	dir := t.TempDir()
	src := "package x\n\n// one\n// two\n// three\nfunc F() {}\n"
	writeFile(t, dir, "a.go", src)
	_, out, _ := runCLI(t, dir)
	if !strings.Contains(out, "a.go:3-5 [func-doc]") {
		t.Errorf("missing line-range address, got: %s", out)
	}
}

func TestRunFixWritesAndStaysGofmtClean(t *testing.T) {
	dir := t.TempDir()
	src := "package x\n\n// CreateOrder creates an order.\nfunc CreateOrder() {}\n"
	p := writeFile(t, dir, "a.go", src)

	code, out, _ := runCLI(t, "--fix", dir)
	if code != 1 {
		t.Errorf("exit = %d, want 1 (PURPOSE placeholder stays report-only)", code)
	}
	if !strings.Contains(out, "fixed ") {
		t.Errorf("missing fixed line, got: %s", out)
	}
	got, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(got), "CreateOrder creates") {
		t.Errorf("comment not deleted: %s", got)
	}
	if !strings.Contains(string(got), "/// <!- FILE: `a.go`") {
		t.Errorf("heading not injected: %s", got)
	}
	assertGofmtClean(t, got)

	// Second run: fixable work is done; only the PURPOSE placeholder remains.
	code2, out2, _ := runCLI(t, "--fix", dir)
	if code2 != 1 {
		t.Errorf("second run exit = %d, want 1 (placeholder)", code2)
	}
	if !strings.Contains(out2, "replace TODO placeholder") {
		t.Errorf("second run missing placeholder report, got: %s", out2)
	}
}

func TestRunFixGeneratedFileUntouched(t *testing.T) {
	dir := t.TempDir()
	src := "// Code generated by foogen. DO NOT EDIT.\n\npackage x\n\n// Generated does things.\nfunc Generated() {}\n"
	p := writeFile(t, dir, "gen.go", src)

	code, out, _ := runCLI(t, "--fix", dir)
	if code != 0 {
		t.Errorf("exit = %d, want 0 (generated skipped, no violations)", code)
	}
	if !strings.Contains(out, "generated skipped: 1") {
		t.Errorf("summary missing generated skip, got: %s", out)
	}
	got, _ := os.ReadFile(p)
	if string(got) != src {
		t.Errorf("generated file must not be modified")
	}
}

func TestRunDiffMode(t *testing.T) {
	dir := t.TempDir()
	src := "package x\n\n// CreateOrder creates an order.\nfunc CreateOrder() {}\n"
	p := writeFile(t, dir, "a.go", src)

	code, out, _ := runCLI(t, "--diff", dir)
	if code != 1 {
		t.Errorf("exit = %d, want 1", code)
	}
	if !strings.Contains(out, "--- a/") || !strings.Contains(out, "+++ b/") {
		t.Errorf("missing unified diff markers, got: %s", out)
	}
	if !strings.Contains(out, "-// CreateOrder creates an order.") {
		t.Errorf("missing deletion line in diff, got: %s", out)
	}
	got, _ := os.ReadFile(p)
	if string(got) != src {
		t.Errorf("diff mode must not write files")
	}
}

func TestRunCleanTreeExitsZero(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "clean.go", "package x\n\n/// <!- FILE: `clean.go`\n/// <!- PURPOSE: Does the thing.\n\nfunc F() {}\n")
	code, out, _ := runCLI(t, dir)
	if code != 0 {
		t.Errorf("exit = %d, want 0", code)
	}
	if !strings.Contains(out, "report-only (manual review): 0") {
		t.Errorf("summary missing zero report-only, got: %s", out)
	}
}

func TestCollectFiles(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, "a.go", "package a\n")
	writeFile(t, dir, "sub/b.go", "package b\n")
	writeFile(t, dir, "sub/deep/c.go", "package c\n")
	writeFile(t, dir, "vendor/v.go", "package v\n")
	writeFile(t, dir, "testdata/t.go", "package t\n")
	writeFile(t, dir, "bin/x.go", "package x\n")
	writeFile(t, dir, "notes.txt", "not go")

	var errb bytes.Buffer
	files := collectFiles([]string{dir}, &errb)
	names := map[string]bool{}
	for _, f := range files {
		names[filepath.Base(f)] = true
	}
	for _, want := range []string{"a.go", "b.go", "c.go"} {
		if !names[want] {
			t.Errorf("missing %s in collected files: %v", want, files)
		}
	}
	for _, no := range []string{"v.go", "t.go", "x.go"} {
		if names[no] {
			t.Errorf("%s should be skipped: %v", no, files)
		}
	}

	// Single .go file arg.
	single := collectFiles([]string{filepath.Join(dir, "a.go")}, &errb)
	if len(single) != 1 || filepath.Base(single[0]) != "a.go" {
		t.Errorf("single file arg: got %v", single)
	}
	// Non-.go file arg is ignored.
	none := collectFiles([]string{filepath.Join(dir, "notes.txt")}, &errb)
	if len(none) != 0 {
		t.Errorf("non-.go file should be ignored: %v", none)
	}
	// Stat error path.
	_ = collectFiles([]string{"/no/such/path"}, &errb)
	if !strings.Contains(errb.String(), "stat /no/such/path") {
		t.Errorf("missing stat error on stderr, got: %s", errb.String())
	}
}

func TestRel(t *testing.T) {
	cwd, _ := os.Getwd()
	if got := rel("./x.go"); got != "x.go" {
		t.Errorf("rel(./x.go) = %q, want x.go", got)
	}
	if got := rel(filepath.Join(cwd, "sub", "x.go")); got != filepath.Join("sub", "x.go") {
		t.Errorf("rel(under cwd) = %q", got)
	}
	if got := rel("/elsewhere/x.go"); got != "/elsewhere/x.go" {
		t.Errorf("rel(outside cwd) = %q, want unchanged", got)
	}
}

func assertGofmtClean(t *testing.T, src []byte) {
	t.Helper()
	formatted, err := format.Source(src)
	if err != nil {
		t.Errorf("gofmt parse error: %v", err)
		return
	}
	if string(formatted) != string(src) {
		t.Errorf("source is not gofmt-clean\nGOT:\n%s\nFMT:\n%s", src, formatted)
	}
}
